# Generated by Django 4.2.6 on 2023-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantDetails', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
