# Generated by Django 4.2.6 on 2023-10-23 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_alter_jobs_jobdesc_alter_jobs_joblocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicantDetails', '0003_alter_applicantdetails_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruiter.jobs')),
            ],
        ),
    ]
