# Generated by Django 4.2.6 on 2023-10-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantDetails', '0004_jobapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='cv',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='cv'),
        ),
    ]
