# Generated by Django 4.2.6 on 2023-10-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_jobs_jobdesc_alter_jobs_joblocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='applicants',
        ),
    ]
