# Generated by Django 4.2.6 on 2023-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_alter_jobs_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobDesc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobLocation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobTitle',
            field=models.CharField(max_length=100),
        ),
    ]
